### PR TITLE
Add benchmarking code and unit tests for full paragraphs

### PR DESCRIPTION
**Pull request by jcbrockschmidt**
This pull request is intended to resolve issue #20.

Benchmarking code is located in `benchmarking` directory with an associated README. Limitation include
 1. Memory usage reported by `memory.py` may vary slightly between runs.
 2. The dataset used by `paragraphs.py` in the `benchmarking/data/paragraphs` directory may not be valid for all versions of `better_profanity`. If some words contained in the default word list are removed, some paragraphs' text may not be censored as expected.

`tox.ini` was updated to include the benchmarking code in the linter check.

The default word list has been modified slightly. Changes from #25 have been incorporated, and words that are invalid as mentioned in #21 have been removed.

Unit tests have been added for
 1. Full paragraphs, with 0%, 5%, 50%, and 100% of words as swear words.
 2. All default words (same as #24)
 3. Punctuation after swear words (same as the unit test proposed in #21 in [this comment](https://github.com/snguyenthanh/better_profanity/issues/21#issuecomment-739639533))

These unit tests were added to account for issues I ran into while creating the benchmarking code. I can split them into separate pull requests if that's preferable.

Depends #25

### CODE REVIEW

**Comment by snguyenthanh** [comment]
What do you think about using third-party libraries for benchmarking ? Such as using [memory-profiler](https://github.com/pythonprofilers/memory_profiler) for memory usage and `pytest-benchmark` for performance ?

Can you also exclude the `benchmarking` dir in `setup.py` ? I think that directory should not be included in the compiled package.

**Comment by jcbrockschmidt** [comment]
@snguyenthanh I'll look into transferring the code to `memory-profiler` and `pytest-benchmark`. At a glance, they look like they should be fine, and its probably best I don't try to reinvent the wheel too much.

Is the `benchmarking` directory currently being installed somewhere? Running `python3 setup.py install --user` doesn't appear to copy any of the benchmarking files to the corresponding `site-packages` directory. It's possible I'm missing something, of course.

**Comment by snguyenthanh** [comment]
> Running python3 setup.py install --user doesn't appear to copy any of the benchmarking files to the corresponding site-packages directory.

Okay then I think it should be safe. I haven't touch the `setup.py` for so long and forgot how it works.

**Comment by jcbrockschmidt** [comment]
The benchmarking scripts now use `memory-profiler` and `pytest-benchmark` as suggested. This should give these new scripts higher reliability and flexibility.

If everything looks good, I recommend merging #25 first since this pull request incorporates it.

**Comment by jcbrockschmidt** [comment]
Rebased with #25, which was just rebased with master.

**Review by snguyenthanh — APPROVED** [review]

**Pull request merged**
