### PR TITLE
Add possibility to check unicode symbols

### PR DESCRIPTION
**Pull request by Derfirm**
Added a label with unicode letters and a test for it.
Unicode is going like this:
```
import sys
import unicodedata
from collections import defaultdict

unicode_category = defaultdict(list)
for c in map(chr, range(sys.maxunicode + 1)):
    unicode_category[unicodedata.category(c)].append(c)
```
And from there on out use that map to translate back to a series of characters for a given category:
```
alphabetic = unicode_category['Ll']
```

### CODE REVIEW

**Comment by snguyenthanh** [comment]
1. Can you please explain why only category `Ll` is used to map the characters ?

2. Moreover, I have the following sentence: `Эффекти́вного противоя́дия от я́да фу́гу не существу́ет до сих пор`. 
It fails to censor word `противоя́дия`. Is this an expected behavior?

**Comment by Derfirm** [comment]
`Ll`  is Letter Lowercase, so yes, I deliberately cut off special characters
Do they really need?

**Comment by Derfirm** [comment]
In your case, a special character is used, called "Combining Diacritical Marks",  which is always called before the letter. Is it worth expanding the list of characters for this case?

**Comment by snguyenthanh** [comment]
May be we should include category `Lu` as well.
I think the problem is not the list of characters, but the way the words merge together.

For example, `blue tree` is a word with an empty space ` ` as the separator. It should treat `противоя́дия` as 1 word with `́` as the separator as well.

**Comment by Derfirm** [comment]
``` (U+0027) «APOSTROPHE» not include as Mn | Mark, Non-Spacing or Mc | Mark, Spacing Combining

**Comment by snguyenthanh** [comment]
I just pushed a commit to a new branch `development`, changing the way the words are merged together.

Currently in `master` branch, the word `hand_job` is treated as 1 word `hard_job`. The newly pushed commit, in `development`, treats it as 2 words `hand` and `job`. This allows a better and more stable comparison between the words.

Could you please change the destination branch of this PR from `master` to `development` ? I tested and it works well for Unicode characters.

**Comment by snguyenthanh** [comment]
Should we include category `Lu` for the Unicode characters as well ?

**Comment by Derfirm** [comment]
import sys 
import unicodedata
import json
```from collections import defaultdict   
unicode_category = defaultdict(list) 

for c in map(chr, range(sys.maxunicode + 1)): 
    unicode_category[unicodedata.category(c)].append(c) 

with open("alphabetic_unicode.json", "w") as js: 
    js.write(json.dumps(unicode_category['Ll'] + unicode_category['Lu'] + unicode_category['Mc'] + unicode_category['Mn'] + unicode_category['Mn'])) 
```

**Comment by snguyenthanh** [comment]
Thanks.
I created a *beta* release for Unicode support, which can be installed by:
```
$ pip install better-profanity==0.3b0
```

Please let me know if it has any issues.

**Pull request merged**
